### ISSUE TITLE
Error ERR_INVALID_ARG_TYPE in xsuaa-to-ams tutorial while doing cds build --production

### ISSUE THREAD

**Issue by GaneshGangatharan** [SAP-samples/btp-developer-guide-cap#118]
INCIDENT-MANAGEMENT % cds build --production 
building project [/Users/MyUser/Documents/GitHub-Tool/INCIDENT-MANAGEMENT], clean [true]
cds-dk [8.3.0], cds [8.3.1], compiler [5.3.2], home [/Users/MyUser/Documents/GitHub-Tool/INCIDENT-MANAGEMENT/node_modules/@sap/cds]

{
  build: {
    target: 'gen',
    tasks: [
      { for: 'hana', src: 'db', options: { model: ['db', 'srv', 'app'] }},
      { for: 'nodejs', src: 'srv', options: { model: ['db', 'srv', 'app'] }},
      { for: 'ams', src: 'srv', options: { model: ['db', 'srv', 'app'] }}
    ]
  }
}

done > wrote output to:
   gen/db/package.json
   gen/db/src/.hdiconfig
   gen/db/src/gen/.hdiconfig
   gen/db/src/gen/.hdinamespace
   gen/db/src/gen/AdminService.Addresses.hdbview
   gen/db/src/gen/AdminService.Customers.hdbview
   gen/db/src/gen/AdminService.Incidents.hdbview
   gen/db/src/gen/AdminService.Incidents_conversation.hdbview
   gen/db/src/gen/AdminService.Status.hdbview
   gen/db/src/gen/AdminService.Status_texts.hdbview
   gen/db/src/gen/AdminService.Urgency.hdbview
   gen/db/src/gen/AdminService.Urgency_texts.hdbview
   gen/db/src/gen/DRAFT.DraftAdministrativeData.hdbtable
   gen/db/src/gen/ProcessorService.Addresses.hdbview
   gen/db/src/gen/ProcessorService.Customers.hdbview
   gen/db/src/gen/ProcessorService.DraftAdministrativeData.hdbview
   gen/db/src/gen/ProcessorService.Incidents.hdbview
   gen/db/src/gen/ProcessorService.Incidents_conversation.hdbview
   gen/db/src/gen/ProcessorService.Incidents_conversation_drafts.hdbtable
   gen/db/src/gen/ProcessorService.Incidents_drafts.hdbtable
   gen/db/src/gen/ProcessorService.Status.hdbview
   gen/db/src/gen/ProcessorService.Status_texts.hdbview
   gen/db/src/gen/ProcessorService.Urgency.hdbview
   gen/db/src/gen/ProcessorService.Urgency_texts.hdbview
   gen/db/src/gen/data/sap.capire.incidents-Addresses.csv
   gen/db/src/gen/data/sap.capire.incidents-Addresses.hdbtabledata
   gen/db/src/gen/data/sap.capire.incidents-Customers.csv
   gen/db/src/gen/data/sap.capire.incidents-Customers.hdbtabledata
   gen/db/src/gen/data/sap.capire.incidents-Incidents.conversation.csv
   gen/db/src/gen/data/sap.capire.incidents-Incidents.conversation.hdbtabledata
   ... 32 more. Run with DEBUG=build to show all files.

TypeError [ERR_INVALID_ARG_TYPE]: The "paths[0]" argument must be of type string. Received undefined
    at Object.resolve (node:path:1129:7)
    at Object.to (/usr/local/lib/node_modules/@sap/cds-dk/lib/build/plugin.js:136:37)
    at Object.compileCds (/Users/MyUser/Documents/GitHub-Tool/INCIDENT-MANAGEMENT/node_modules/@sap/ams-dev/src/cap/capAmsFlow.js:27:30)
    at async AmsBuildPlugin.build (/Users/MyUser/Documents/GitHub-Tool/INCIDENT-MANAGEMENT/node_modules/@sap/ams-dev/src/cap/AmsBuildPlugin.js:39:3)
    at async Promise.allSettled (index 0)
    at async BuildTaskEngine._executePipeline (/usr/local/lib/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:159:29)
    at async BuildTaskEngine._executeBuildTasks (/usr/local/lib/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:150:25)
    at async BuildTaskEngine.processTasks (/usr/local/lib/node_modules/@sap/cds-dk/lib/build/buildTaskEngine.js:59:33)
    at async build (/usr/local/lib/node_modules/@sap/cds-dk/lib/build/index.js:19:16)
    at async Object.build (/usr/local/lib/node_modules/@sap/cds-dk/bin/build.js:171:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by singhabhi1999** [comment]
Hi @GaneshGangatharan ,

can you please share with me the application latest codebase. I need to check the application configurations.

Regards,
Abhinav

**Comment by miyasuta** [comment]
@singhabhi1999 
I am experiencing the same issue. My repository URL is below (branch: ams).
https://github.com/miyasuta/incident-management-2411

**Comment by miyasuta** [comment]
@singhabhi1999 
Could you please confirm whether the position of `AMS_DCL_ROOT` in mta.yaml below is correct?

```
- name: incident-management-srv
  type: nodejs
  path: gen/srv
  requires:
  - name: incident-management-db
  - name: incident-management-auth
    parameters:
      config:
         credential-type: "X509_GENERATED"
  properties:
    AMS_DCL_ROOT: ams/dcl
```

**Comment by miyasuta** [comment]
@singhabhi1999 
I have updated the versions of **@sap/ams** and **@sap/ams-dev** to 2.0.0. However, the build error still persists.

```
...
   gen/srv/srv/csn.json
   gen/srv/srv/odata/v4/AdminService.xml
   gen/srv/srv/odata/v4/ProcessorService.xml

[ERROR] Unexpected error during CDS to DCL compilation: The "path" argument must be of type string. Received undefined

CDS build failed
[2025-01-06 05:30:22] ERROR the "before-all"" build failed: could not execute the "npx cds build --production" command: exit status 1
make: *** [Makefile_20250106053015.mta:28: pre_build] Error 1
[2025-01-06 05:30:22] ERROR could not build the MTA project: could not execute the "make -f Makefile_20250106053015.mta p=cf mtar= strict=true mode=" command: exit status 2
Error: could not build the MTA project: could not execute the "make -f Makefile_20250106053015.mta p=cf mtar= strict=true mode=" command: exit status 2
```

**Comment by singhabhi1999** [comment]
Hi @miyasuta ,

I'm sorry for not getting back to you sooner. Now we have CDS add commands for IAS and AMS, which will solve a lot of issues for us. Can you please try starting a fresh trial of the scenario? 
However, for this issue can you please check if you have following configurations:
https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/xsuaa-to-ams/3-deploy-to-cf.md#:~:text=%7D%2C%0A%0A...%0A%7D-,Change%20the,-auth.kind%20to

**Comment by miyasuta** [comment]
@singhabhi1999 
Thank you for your reply. I started with a fresh project with sap/cds-dk version 8.7.2, and the build & deploy was successful.
The procedure was:
- Add AMS and IAS configurations with `cds add ams`
- Update mta.yaml as in the [code in my repo]((https://github.com/miyasuta/incident-management-2502/blob/ams/mta.yaml)) (I didn't create `ias-config.json` as the configurations were already added to the mta.yaml)
- Build & Deploy

**Comment by singhabhi1999** [comment]
@miyasuta , Since the issue is not valid anymore, can you please close the ticket from your side.

**Comment by miyasuta** [comment]
@singhabhi1999 
I don't have the permission to close this ticket. Maybe @GaneshGangatharan can close it.
